plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.novabeat.music"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.novabeat.music"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    // Lifecycle
    implementation(libs.androidx.lifecycle.runtime.ktx)
    // Coroutines
    implementation(libs.androidx.coroutines.android)
    // Media3 ExoPlayer
    implementation(libs.exoplayer.common)
    implementation(libs.exoplayer.session)
    implementation(libs.exoplayer.core)
    implementation(libs.exoplayer.ui)
    // Glide
    implementation(libs.glide)
    annotationProcessor(libs.glide)
    // Gson
    implementation(libs.gson)
}
